README.md
=> Include a README with usage and short introduction

README.md
=> Update README with multiline examples

Cargo.lock, Cargo.toml
=> Update dependencies and Cargo.toml description

Cargo.lock, Cargo.toml, src/bin/fatrw/main.rs
=> Compatibility with Rust 1.36

src/bin/fatrw/main.rs, src/bin/fatrw/opts.rs
=> Write operation receives content from stdin

src/bin/fatrw/main.rs, src/bin/fatrw/opts.rs, src/copy.rs, src/fs.rs, src/lib.rs, src/write.rs
=> Copy subcommand

.github/workflows/ci.yml
=> Refine when to trigger builds

repo.yml
=> Change balena project type to rust-public-crate

src/bin/fatrw/main.rs
=> Simpler log formatting

src/bin/fatrw/cli.rs, src/bin/fatrw/main.rs, src/fs.rs
=> Add debug CLI argument

Cargo.toml
=> Add package.repository in Cargo.toml

Cargo.toml
=> Use name and email in package.authors in Cargo.toml

Cargo.toml, src/bin/fatrw/cli.rs, src/bin/fatrw/main.rs, src/checksum.rs, src/fs.rs, src/lib.rs, src/random.rs, tests/integration.rs
=> Verbose clippy warnings

src/fs.rs, src/lib.rs, src/random.rs, src/read.rs
=> Fix clippy lints on Rust v1.65

.github/workflows/ci.yml
=> Replace actions-rs/cargo build with direct cross usage

.github/workflows/ci.yml
As shown in action's examples.
=> Switch to rust-toolchain@master

.github/workflows/flowzone.yml
=> Fix flowzone Rust toolchain to 1.67

repo.yml
Signed-off-by: Kyle Harding <kyle@balena.io>
=> Add repo yml to fix versionist errors

repo.yml
Signed-off-by: Kyle Harding <kyle@balena.io>
=> Fix repo.yml to be proper yaml

Cargo.lock, Cargo.toml
=> Bump clap to v4
